### ISSUE TITLE
Source Code Update Required 

### ISSUE THREAD

**Issue by Mridumoloy** [MXVideoPlayer/MX-FFmpeg#10]
Please update the source code as the new update has broken compatibility with the Custom Codecs especially the one by USBHost. And because of this people aren't able to play AC3 or EAC3 audio files

**Comment by fredgolightly** [comment]
Update please

**Comment by procobain** [comment]
Update please.

**Comment by Gggggggggfdd** [comment]
@MXVideoPlayer @Thirumalai you get solution??

**Comment by jhlcw** [comment]
> Update please.
try this,it works.
https://github.com/daugustin/MX-FFmpeg/releases

**Comment by Gggggggggfdd** [comment]
@Thirumalai  Releases your zip file🙂

**Comment by Gggggggggfdd** [comment]
@Thirumalai @MXVideoPlayer releases your zip file
