### ISSUE TITLE
Please update the sourcecode

### ISSUE THREAD

**Issue by jhlcw** [MXVideoPlayer/MX-FFmpeg#9]
MXPlayer Pro 1.86.0,cannot load the old codec,please update the sourcecode

**Comment by HBP87** [comment]
@MXVideoPlayer Please do it. I am not able to play videos with ac3 audio, on the latest 1.85.x mx player pro.

**Comment by Gggggggggfdd** [comment]
What is the solution??

**Comment by Gggggggggfdd** [comment]
> MXPlayer Pro 1.86.0,cannot load the old codec,please update the sourcecode

you get Solution?

**Comment by jhlcw** [comment]
> > MXPlayer Pro 1.86.0,cannot load the old codec,please update the sourcecode
> 
> you get Solution?

https://github.com/MXVideoPlayer/MX-FFmpeg/issues/9#issuecomme

> > MXPlayer Pro 1.86.0,cannot load the old codec,please update the sourcecode
> 
> you get Solution?

try this
https://github.com/daugustin/MX-FFmpeg/releases

**Comment by Gggggggggfdd** [comment]
@jhlcw it is working thanks_

**Comment by jhlcw** [comment]
> @jhlcw it is working thanks_

😁😁😁
